{% set data = load_setup_py_data() %}

package:
    name: nba_crawler
    version: {{ data.get('version') }}


source:
  path: .


build:
  number: 0
  script: invoke install


requirements:
    develop:
      - python
      - asynctest==0.13.0
      - autoflake==1.3
      - black==19.10b0
      - conda-build==3.18.12
      - conda-verify==3.1.1
      - flake8==3.8.4
      - flake8-mutable==1.2.0
      - invoke==1.5.0
      - isort==5.6.4
      - m2r2==0.2.7
      - mypy==0.790
      - pytest==6.2.1
      - pytest-asyncio==0.14.0
      - pytest-cov==2.10.1
      - pytest-mock==3.4.0
      - setuptools==49.6.0

    build:
      - python
      - invoke==1.5.0

    run:
      - python
      - click>=7.1.2
      - aiohttp
      - requests
      - loguru
      - pandas
      - pyarrow
